services:
  api:
    container_name: quadra-api
    image: quadra-api
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@quadra-postgres:5432/quadra?schema=public
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - quadra-network

networks:
  quadra-network:
    external: true
    name: quadra-network

volumes:
  node_modules:
