FROM node:22-alpine
ENV NODE_ENV=development
WORKDIR /home/node/app

COPY package*.json prisma.config.ts ./
COPY prisma ./prisma

RUN npm ci --no-audit --no-fund \
    --fetch-retries=5 \
    --fetch-retry-mintimeout=20000 \
    --fetch-retry-maxtimeout=120000

RUN npm run prisma:generate

COPY --chown=node:node . .

USER node
CMD ["npm", "run", "start:dev"]
