FROM node:22-alpine
ENV NODE_ENV=development
WORKDIR /home/node/app

COPY package*.json prisma.config.ts ./
COPY prisma ./prisma

RUN npm ci && npx prisma generate

COPY --chown=node:node . .

USER node
CMD ["npm", "run", "start:dev"]
