FROM node:22-alpine
ENV NODE_ENV=development
USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node package*.json prisma.config.ts ./
COPY --chown=node:node prisma ./prisma
RUN npm install && npx prisma generate
COPY --chown=node:node . .
CMD ["npm", "run", "start:dev"]
